### ISSUE TITLE
Internal compiler error while trying to compile on macOS Mojave

### ISSUE THREAD

**Issue by gdeskos** [LHEEA/Grid2Grid#4]
Dear all,

I am trying to install Grid2Grid using cmake and following the instructions in this GitHub repo. I get an internal compiler error  while trying to compile mfpGoemtry.f90 (see attachments). I am using the GNU gfortran 9.2.0  with fftw3 and hdf5. Any suggestion ?

Best,
George

![Screen Shot 2020-01-27 at 1 57 56 PM](https://user-images.githubusercontent.com/15731572/73213207-0acfeb00-410d-11ea-9abd-5bf3ebf13a88.png)

![Screen Shot 2020-01-27 at 1 51 06 PM](https://user-images.githubusercontent.com/15731572/73212848-55049c80-410c-11ea-9f0b-472c92f26bf8.png)

**Comment by YoungmChoi** [comment]
Dear George (@gdeskos)

It seems that the class destroyer is not working in a recent version gfortran. I'll check this after I updated to a recent version. 

For now, please try to comment on the type procedures "final" in the libFyMc/geometry folder, then compile Grid2Grid again. I found the class destroyer is defined for "libFyMc/baseGeometry/panel.typ" and "libFyMc/surfMesh/typ". For example, please comment 

libFyMc/baseGeometry/panel.typ 
        !! Destructor
        final :: finalPanel
to be 
       !! Destructor
!        final :: finalPanel

If you still have a problem after trying this, please let us know. 

Best Regards, 
Young-Myung Choi

**Comment by gdeskos** [comment]
It worked, thanks!
