### ISSUE TITLE
Compile/linking error

### ISSUE THREAD

**Issue by nbasse** [LHEEA/Grid2Grid#5]
Hi! 
Thank you for sharing this software open source!
I'm looking forward to trying it out in combination with HOS-ocean 😀

I've had some different issues compiling the software, but I have managed to solve a lot of them and are now stuck on what I think is the final step.
I get some linking error regarding the FFT library, and haven't been able to find any answers on google.

Here is the output/error I get:

$ cmake --build build
Scanning dependencies of target bspline                                                                              
[  4%] Building Fortran object src/libBspline/CMakeFiles/bspline.dir/src/bspline_sub_module.f90.o                    
[  8%] Building Fortran object src/libBspline/CMakeFiles/bspline.dir/src/bspline_oo_module.f90.o                     
[ 12%] Building Fortran object src/libBspline/CMakeFiles/bspline.dir/src/bspline_module.f90.o                        
[ 16%] Linking Fortran static library ../../../lib/libbspline.a                                                      
[ 16%] Built target bspline                                                                                          
Scanning dependencies of target fymc                                                                                 
[ 20%] Building Fortran object src/libFyMc/CMakeFiles/fymc.dir/src/mfpGlobal.f90.o                                   
[ 24%] Building Fortran object src/libFyMc/CMakeFiles/fymc.dir/src/general/mfpGeneral.f90.o                          
[ 28%] Building Fortran object src/libFyMc/CMakeFiles/fymc.dir/src/geometry/mfpGeometry.f90.o                        
[ 32%] Linking Fortran static library ../../../lib/libfymc.a                                                         
[ 32%] Built target fymc                                                                                             
Scanning dependencies of target postG2G                                                                              
[ 36%] Building Fortran object src/libGrid2Grid/CMakeFiles/postG2G.dir/modGrid2GridGlobal.f90.o                      
[ 40%] Building Fortran object src/libGrid2Grid/CMakeFiles/postG2G.dir/HDF5/modHDF5Interface.f90.o                   
[ 44%] Building Fortran object src/libGrid2Grid/CMakeFiles/postG2G.dir/fftw3/modFourier_r2c_FFTW3.f90.o              
[ 48%] Building Fortran object src/libGrid2Grid/CMakeFiles/postG2G.dir/surf2Vol/modSurf2Vol.f90.o                    
[ 52%] Building Fortran object src/libGrid2Grid/CMakeFiles/postG2G.dir/vol2Vol/modVol2Vol.f90.o                      
[ 56%] Building Fortran object src/libGrid2Grid/CMakeFiles/postG2G.dir/modGrid2Grid.f90.o                            
[ 60%] Building Fortran object src/libGrid2Grid/CMakeFiles/postG2G.dir/postGrid2Grid/modPostGrid2Grid.f90.o          
[ 64%] Building Fortran object src/libGrid2Grid/CMakeFiles/postG2G.dir/main.f90.o                                    
[ 68%] Linking Fortran executable ../../../postG2G                                                                   
[ 68%] Built target postG2G                                                                                          
Scanning dependencies of target Grid2Grid                                                                            
[ 72%] Building Fortran object src/libGrid2Grid/CMakeFiles/Grid2Grid.dir/modGrid2GridGlobal.f90.o                    
[ 76%] Building Fortran object src/libGrid2Grid/CMakeFiles/Grid2Grid.dir/HDF5/modHDF5Interface.f90.o                 
[ 80%] Building Fortran object src/libGrid2Grid/CMakeFiles/Grid2Grid.dir/fftw3/modFourier_r2c_FFTW3.f90.o            
[ 84%] Building Fortran object src/libGrid2Grid/CMakeFiles/Grid2Grid.dir/surf2Vol/modSurf2Vol.f90.o                  
[ 88%] Building Fortran object src/libGrid2Grid/CMakeFiles/Grid2Grid.dir/vol2Vol/modVol2Vol.f90.o                    
[ 92%] Building Fortran object src/libGrid2Grid/CMakeFiles/Grid2Grid.dir/modGrid2Grid.f90.o                          
[ 96%] Building Fortran object src/libGrid2Grid/CMakeFiles/Grid2Grid.dir/postGrid2Grid/modPostGrid2Grid.f90.o        
[100%] Linking Fortran shared library ../../../lib/libGrid2Grid.so                                                   
/usr/bin/ld: /usr/local/lib/libfftw3.a(f77api.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC                                                                                
/usr/local/lib/libfftw3.a: error adding symbols: Bad value                                                           
collect2: error: ld returned 1 exit status                                                                           
src/libGrid2Grid/CMakeFiles/Grid2Grid.dir/build.make:201: recipe for target '../lib/libGrid2Grid.so' failed          
make[2]: *** [../lib/libGrid2Grid.so] Error 1                                                                        
CMakeFiles/Makefile2:240: recipe for target 'src/libGrid2Grid/CMakeFiles/Grid2Grid.dir/all' failed                   
make[1]: *** [src/libGrid2Grid/CMakeFiles/Grid2Grid.dir/all] Error 2                                                 
Makefile:149: recipe for target 'all' failed                                                                         
make: *** [all] Error 2 

All and any ideas on how to solve this are really appreciated.
Thanks!

Best Regards,
Niclas

**Comment by YoungmChoi** [comment]
Dear Niclas, 

It seems that "libfftw3.a" does not exist in "/usr/local/lib/". You can make a soft link or you can set the installation path manually. 

Can you check that "libfftw3.a" exists in "/usr/local/lib/"? If it does not exist, you need to specify the path for "libfftw3.a". You can manually set this by changing inside of CMakeLists.txt.

original : 
    set(FFTW3_LIB_PATH **/usr/local/lib**) 

modification:
   set(FFTW3_LIB_PATH  **FFTW3_LIBRARY_INSTALLATION_PATH**)  

or defining the path as:

cmake -H. -Bbuild -DFFTW3_LIB_PATH=FFTW3_LIBRARY_INSTALLATION_PATH

Please have a try and let us know. Have a nice day!

Best regards, 
Young-Myung Choi

**Comment by nbasse** [comment]
@YoungmChoi 
Dear Young-Myung, 
Thank you for your quick reply!

from what I can see libfftw3.a actually exist in the specified folder:

`$ ls -la /usr/local/lib/ | grep fftw3`
`-rw-r--r-- 1 root root   2280560 Feb 17 13:49 libfftw3.a`
`-rwxr-xr-x 1 root root       886 Feb 17 13:49 libfftw3.la`

Do you have any other ideas on how to solve this?

Kind Regards,
Niclas

**Comment by YoungmChoi** [comment]
Dear Niclas, 

Sorry. I misunderstood the error message. You need to compile "libfftw3.a" with a flag "-fPIC".
There is an explanation in the manual on how to compile this library with this flag.

Please try compilation after recompiling the "libfftw3.a".

Have a nice day.

Best regards, 
Young-Myung Choi

**Comment by nbasse** [comment]
Thanks! 
I just noticed this also. I had previously compiled fftw3 when I installed HOS-ocean and didn't nee need the flag then. 
I have just recompiled fftw3 and made a successful compilation of grid2grid!
Now I will try it out 😀

Thank you for our assistance!
Have a nice day!

Best regards,
Niclas
